# Generated by Django 5.2.7 on 2025-10-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_country', models.CharField(max_length=64)),
                ('destination_country', models.CharField(max_length=64)),
                ('no_of_days', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
