# Generated by Django 5.2.7 on 2025-10-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
